"""
2D Causal Dynamical Triangulations (CDT).

CDT is a lattice approach to quantum gravity where spacetime is built from
simplices (triangles in 2D) with a preferred time foliation.

In 2D CDT:
- Time is divided into discrete slices t = 0, 1, ..., T
- Each time slice is a ring of s_t spatial edges
- Between consecutive slices, triangles fill the space
- Two types of triangles: (2,1) with 2 vertices at time t and 1 at t+1,
  and (1,2) with 1 vertex at time t and 2 at t+1
- The triangulation is generated by a birth/death process on the strip

The partition function is: Z = sum over triangulations T of exp(-S_R[T])
where S_R is the Regge action (discretization of Einstein-Hilbert).

In 2D: S_R = lambda_2 * N_2 (just counts triangles, since 2D gravity is topological)
where lambda_2 is the cosmological constant coupling and N_2 = total triangles.

Reference: Ambjorn, Jurkiewicz, Loll, "A Nonperturbative Lorentzian Path
Integral for Gravity", Phys. Rev. Lett. 85 (2000) 924
"""

import numpy as np


class CDT2D:
    """
    2D CDT triangulation with cylindrical topology (periodic spatial slices).
    """

    def __init__(self, T: int = 20, s_init: int = 10):
        """
        Initialize with T time slices, each starting with s_init spatial edges.
        """
        self.T = T
        # s[t] = number of spatial edges at time slice t
        self.s = np.full(T, s_init, dtype=int)

    @property
    def total_triangles(self) -> int:
        """Total number of triangles. Between slices t and t+1:
        n_triangles = s[t] + s[t+1] (for cylindrical topology)."""
        total = 0
        for t in range(self.T - 1):
            total += self.s[t] + self.s[t + 1]
        return total

    @property
    def total_vertices(self) -> int:
        return int(np.sum(self.s))

    def regge_action(self, lambda2: float = 0.0) -> float:
        """
        Regge action in 2D: S = lambda2 * N_2 + (other terms).
        In pure 2D gravity the action is topological, so we use
        the cosmological constant term only.
        """
        return lambda2 * self.total_triangles

    def volume_profile(self) -> np.ndarray:
        """Return the spatial volume (number of edges) at each time slice."""
        return self.s.copy()


def mcmc_cdt(T: int = 20, s_init: int = 10, lambda2: float = 0.0,
             n_steps: int = 10000, target_volume: int = None,
             mu: float = 0.0,
             rng: np.random.Generator = None) -> list:
    """
    MCMC sampling of 2D CDT triangulations.

    Moves:
    1. Add a vertex to slice t (s[t] -> s[t]+1 and s[t+1] -> s[t+1]+1)
       This adds 2 triangles.
    2. Remove a vertex from slice t (s[t] -> s[t]-1 and s[t+1] -> s[t+1]-1)
       This removes 2 triangles. Only if s[t] > 2 and s[t+1] > 2.

    With a volume-fixing term: S_total = S_R + mu * (N - N_target)^2

    Parameters:
    - lambda2: cosmological constant coupling
    - mu: volume-fixing strength
    - target_volume: target total number of vertices (if None, free volume)
    """
    if rng is None:
        rng = np.random.default_rng()

    if target_volume is None:
        target_volume = T * s_init

    cdt = CDT2D(T, s_init)
    samples = []

    # Current action
    def action(c):
        S = c.regge_action(lambda2)
        if mu > 0:
            S += mu * (c.total_vertices - target_volume) ** 2
        return S

    S_current = action(cdt)

    for step in range(n_steps):
        # Choose a random time slice
        t = rng.integers(0, T - 1)

        # Choose move: add or remove vertex
        if rng.random() < 0.5:
            # Add vertex at slice t
            cdt.s[t] += 1
            S_new = action(cdt)
            delta_S = S_new - S_current

            if delta_S <= 0 or rng.random() < np.exp(-delta_S):
                S_current = S_new
            else:
                cdt.s[t] -= 1  # reject
        else:
            # Remove vertex at slice t (if possible)
            if cdt.s[t] > 2:
                cdt.s[t] -= 1
                S_new = action(cdt)
                delta_S = S_new - S_current

                if delta_S <= 0 or rng.random() < np.exp(-delta_S):
                    S_current = S_new
                else:
                    cdt.s[t] += 1  # reject

        # Save sample periodically
        if step % 10 == 0:
            samples.append(cdt.volume_profile())

    return samples


def spectral_dimension_cdt(volume_profile: np.ndarray,
                            sigma_range=(0.1, 100.0), n_sigma=50) -> tuple:
    """
    Compute spectral dimension of a CDT configuration.

    Build the graph: vertices on each time slice connected in a ring,
    plus connections between consecutive slices.

    For efficiency, use the Laplacian eigenvalues.
    """
    T = len(volume_profile)
    N = int(np.sum(volume_profile))

    if N > 2000:
        return np.array([]), np.array([])

    # Build adjacency matrix
    adj = np.zeros((N, N), dtype=float)

    # Map: vertex index from (t, i) where i is position within slice t
    offsets = np.zeros(T + 1, dtype=int)
    for t in range(T):
        offsets[t + 1] = offsets[t] + volume_profile[t]

    # Spatial edges (ring at each slice)
    for t in range(T):
        s_t = volume_profile[t]
        for i in range(s_t):
            v1 = offsets[t] + i
            v2 = offsets[t] + (i + 1) % s_t
            adj[v1, v2] = 1
            adj[v2, v1] = 1

    # Timelike edges (between consecutive slices)
    for t in range(T - 1):
        s_t = volume_profile[t]
        s_tp1 = volume_profile[t + 1]
        # Connect each vertex at t to corresponding vertices at t+1
        # Simple scheme: connect vertex i at t to vertex floor(i * s_{t+1}/s_t) at t+1
        for i in range(s_t):
            j = int(i * s_tp1 / s_t) % s_tp1
            v1 = offsets[t] + i
            v2 = offsets[t + 1] + j
            adj[v1, v2] = 1
            adj[v2, v1] = 1
            # Also connect to j+1 for triangulation
            j2 = (j + 1) % s_tp1
            v3 = offsets[t + 1] + j2
            adj[v1, v3] = 1
            adj[v3, v1] = 1

    # Normalized Laplacian
    degree = np.sum(adj, axis=1)
    mask = degree > 0
    adj_c = adj[np.ix_(mask, mask)]
    degree_c = degree[mask]
    n_c = len(degree_c)

    if n_c < 5:
        return np.array([]), np.array([])

    d_inv_sqrt = np.diag(1.0 / np.sqrt(degree_c))
    L = np.eye(n_c) - d_inv_sqrt @ adj_c @ d_inv_sqrt
    eigenvalues = np.linalg.eigvalsh(L)
    eigenvalues = np.clip(eigenvalues, 0, None)

    sigmas = np.logspace(np.log10(sigma_range[0]), np.log10(sigma_range[1]), n_sigma)
    P = np.zeros(n_sigma)
    for idx, sigma in enumerate(sigmas):
        P[idx] = np.mean(np.exp(-eigenvalues * sigma))

    ln_P = np.log(P + 1e-300)
    ln_sigma = np.log(sigmas)
    d_s = -2 * np.gradient(ln_P, ln_sigma)

    return sigmas, d_s
